### ISSUE TITLE
Map recentering has a weird behavior

### ISSUE THREAD

**Issue by jschmid** [cyrilmottier/Polaris#1]
This happened to me with the sample app, but clearly is coming from the lib itself.

Here is how to reproduce it:
- Open the app
- Move the map so that the New York marker is on the far right, where you can barely see it.
- Click on the New York marker.
- The map scrolls all the way to the right to come back almost were it was.

I would expect it to only scroll a few pixels to the left, just to let the callout be visible.

**Comment by cyrilmottier** [comment]
Are you located in NYC? The sample app has user tracking enabled so once a new fix is received it moves the map to make it visible. That may be a reason.

Do you have a way to make a screencast/video of the strange behavior?

**Comment by jschmid** [comment]
I am located in Switzerland. It also does it with the GPS off. I don't think this is related.

I think you can easily reproduce it using the steps I gave.

I'll try to make a video tonight.

**Comment by cyrilmottier** [comment]
@jschmid: Do you have more information on this bug? A video showing the bug in action? The version of your Android? The device you are running Polaris on?

**Comment by jschmid** [comment]
Sorry, I thought you reproduced it successfully since you tagged it as a bug.

See http://youtu.be/9e3DGYnwjEY
(The video is still processing by the time of writing)

The first click is a normal click.
The second one is the faulty one. You can see that the map goes all the way to the right instead of just going a few pixels to the left.
The third click is a normal one. the map moves to the right so that one can see the callout. I think the same thing should happen on the second click, but it should go to the left, not to the right.

Do you see what I mean?

**Comment by jschmid** [comment]
This is a galaxy nexus 4.1.2, but i don't think it matters.

**Comment by cyrilmottier** [comment]
Thank you very much for the video. I can see what you are talking about now.

So, I hate to say that but I think there is no way to fix this bug simply because it is not related to Polaris. It's actually a bug that comes from the Google Maps framework an,d more specifically the `animateTo(GeoPoint)` method in `MapController` :(.

See [MapViewUtil](https://github.com/cyrilmottier/Polaris/blob/master/library/src/com/cyrilmottier/polaris/MapViewUtils.java#L54) for more information on it

**Comment by cyrilmottier** [comment]
Unfixable

Smooth per-pixel scrolling internally uses `MapController.animateTo(GeoPoint)` which is responsible for the weird animation. No way to fix this.
