### ISSUE TITLE
Add Map Tap listener

### ISSUE THREAD

**Issue by robbypond** [cyrilmottier/Polaris#14]
It would be nice if an listener could be added that would fire on a basic Map simple tap, similar to the [onTap](https://developers.google.com/maps/documentation/android/reference/com/google/android/maps/Overlay#onTap%28com.google.android.maps.GeoPoint,%20com.google.android.maps.MapView%29) method of the existing Overlay class.

**Comment by cyrilmottier** [comment]
When using Polaris, I don't really understand the need of listening to taps on the PolarisMapView as callouts are automatically managed. However, if you really want to listen to an `onTap` you still can add your own `Overlay` to the `PolarisMapView`.

Could you please provide more information on why and how this could really improve Polaris? Thank you
