### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by arturdryomov** [cyrilmottier/Polaris#2]
What about Maven? I see you don’t use it, but who knows… :-)

It would be perfect to push the library to Maven Central of course, but Polaris uses Google Maps SDK which doesn’t exist in Central, so pushing isn’t possible yet.

**Comment by arturdryomov** [comment]
If you’ll decide to accept this enhancement I could try to prepare a pull request.

**Comment by ened** [comment]
Couldn't it be pushed to Sonatype, same like ABS?

**Comment by arturdryomov** [comment]
Actually ABS Maps Plugin isn’t in Central for the [reason](https://github.com/JakeWharton/ActionBarSherlock-Plugin-Maps#including-in-your-project) I described before. Artifact with a not available dependency isn’t a very nice solution for anyone.

**Comment by joncfoo** [comment]
You could set up a google code project (or wherever else) that mimics a maven repository so you can deploy the artifact there.  Others can then include this custom repo in their pom.xml
