### ISSUE TITLE
Typo in MapCalloutDrawable

### ISSUE THREAD

**Issue by MikolajKakol** [cyrilmottier/Polaris#23]
Hi,

in MapCalloutDrawable.java you have method in which you are getting mLeftCapDrawable width rather than height

```
@Override
public int getIntrinsicHeight() {
    return Math.max(mLeftCapDrawable.getIntrinsicWidth(),
            Math.max(mBottomAnchorDrawable.getIntrinsicHeight(), mRightCapDrawable.getIntrinsicHeight()));
}
```

**Comment by cyrilmottier** [comment]
Definitely a bug! Thank you. Any pull request would be highly appreciated :)

**Comment by MikolajKakol** [comment]
I've added pull request.

**Comment by cyrilmottier** [comment]
Will be merged in the next release
