### ISSUE TITLE
Polaris + ActionbarSherlock

### ISSUE THREAD

**Issue by rfmussa** [cyrilmottier/Polaris#26]
How can I use this library with actionbarsherlock? i always get classnotfound when i extend SherlockMapActivity

**Comment by cyrilmottier** [comment]
There is no problem using Polaris with ActionBarSherlock. I guess you are using ActionBarSherlock without the "Maps" plugin. Got to https://github.com/JakeWharton/ActionBarSherlock-Plugin-Maps and check it out !

**Comment by rfmussa** [comment]
Nice, i thought the problem was from ABS but it actually is not, I get the same error when running the Sample from the lib(with and without SherlockMapActivity).  FATAL EXCEPTION: main
        java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.cyrilmottier.android.polarissample/com.cyrilmottier.android.polarissample.MainActivity}: java.lang.ClassNotFoundException: com.cyrilmottier.android.polarissample.MainActivity

**Comment by rfmussa** [comment]
ok solved it, library was not correctly included!thanks
