### ISSUE TITLE
Wrong @Override in MapCalloutView

### ISSUE THREAD

**Issue by Amedio** [cyrilmottier/Polaris#28]
Hello Cyril,

I've been trying Polaris on one app of mine, and I found, when adding it to my project, that you where implementing the function setBackground overriding it from ViewGroup in the class MapCalloutView.

Eclipse recommended me to delete de @Override tag, because there was no such function in parent class.

I don't know why is this, if it is a bug from Polaris library, or a bug from Eclipse.

See you, and thank you!

**Comment by cyrilmottier** [comment]
You need to compile the library against the latest SDK. In the latest SDK setBackground(Drawable) has been added.
