### ISSUE TITLE
dismissing calloutview and try to open it again...

### ISSUE THREAD

**Issue by fvisticot** [cyrilmottier/Polaris#30]
I have added an Annotation object with title / subtitle to the mapview
I can click on the marker and the calloutview is correctly displayed.

The onAnnotationClicked callback is correctly called when I click on the calloutView.

In the onAnnotationClicked method, I would like to close this current calloutview.
For that, I'm using:
the calloutView.dismiss(Boolean.FALSE);

The callout is correctly closed but I need to wait several seconds before he could be displayed again...

Is it due to a wrong method call to close the callout view ?

**Comment by cyrilmottier** [comment]
Have you tried calling `mPolarisMapView.setSelectedAnnotation(PolarisMapView.INVALID_POSITION)` instead ?

**Comment by fvisticot** [comment]
Works fine with setSelectedAnnotation !!

Tx a LOT
